version: '3.8'

services:
  barman:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barman
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./barman.conf:/etc/barman.conf
      - ./barman.d:/etc/barman.d
      - ./backups:/var/lib/barman
      - ./crontab:/etc/crontab
    restart: always


